/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_step2hell_jni_SubActivity */

#ifndef SUB_H
#define SUB_H
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_step2hell_jni_SubActivity
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_step2hell_jni_SubActivity_hello
        (JNIEnv *, jobject);

/*
 * Class:     com_step2hell_jni_SubActivity
 * Method:    getPriceOfBook
 * Signature: (Lcom/step2hell/jni/Book;)F
 */
JNIEXPORT jfloat JNICALL Java_com_step2hell_jni_SubActivity_getPriceOfBook
        (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif